# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skeleton.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1208, 859)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(140, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(10, 130, 93, 28))
        self.start_button.setObjectName("start_button")
        self.topics_label = QtWidgets.QLabel(Form)
        self.topics_label.setGeometry(QtCore.QRect(20, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.topics_label.setFont(font)
        self.topics_label.setObjectName("topics_label")
        self.context_label = QtWidgets.QLabel(Form)
        self.context_label.setGeometry(QtCore.QRect(240, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.context_label.setFont(font)
        self.context_label.setObjectName("context_label")
        self.raw_text_label = QtWidgets.QLabel(Form)
        self.raw_text_label.setGeometry(QtCore.QRect(510, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.raw_text_label.setFont(font)
        self.raw_text_label.setObjectName("raw_text_label")
        self.topics_view = QtWidgets.QTextBrowser(Form)
        self.topics_view.setGeometry(QtCore.QRect(10, 200, 191, 391))
        self.topics_view.setObjectName("topics_view")
        self.context_view = QtWidgets.QTextBrowser(Form)
        self.context_view.setGeometry(QtCore.QRect(220, 200, 201, 391))
        self.context_view.setObjectName("context_view")
        self.raw_text_view = QtWidgets.QTextBrowser(Form)
        self.raw_text_view.setGeometry(QtCore.QRect(440, 200, 221, 391))
        self.raw_text_view.setObjectName("raw_text_view")
        self.subreddit_input_label = QtWidgets.QLabel(Form)
        self.subreddit_input_label.setGeometry(QtCore.QRect(20, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subreddit_input_label.setFont(font)
        self.subreddit_input_label.setObjectName("subreddit_input_label")
        self.subreddit_input = QtWidgets.QLineEdit(Form)
        self.subreddit_input.setGeometry(QtCore.QRect(140, 10, 141, 31))
        self.subreddit_input.setObjectName("subreddit_input")
        self.avg_polarity_overall_label = QtWidgets.QLabel(Form)
        self.avg_polarity_overall_label.setGeometry(QtCore.QRect(670, 310, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_polarity_overall_label.setFont(font)
        self.avg_polarity_overall_label.setObjectName("avg_polarity_overall_label")
        self.auto_process_button = QtWidgets.QPushButton(Form)
        self.auto_process_button.setGeometry(QtCore.QRect(130, 130, 91, 31))
        self.auto_process_button.setObjectName("auto_process_button")
        self.avg_title_label = QtWidgets.QLabel(Form)
        self.avg_title_label.setGeometry(QtCore.QRect(670, 400, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_title_label.setFont(font)
        self.avg_title_label.setObjectName("avg_title_label")
        self.avg_post_label = QtWidgets.QLabel(Form)
        self.avg_post_label.setGeometry(QtCore.QRect(670, 350, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_post_label.setFont(font)
        self.avg_post_label.setObjectName("avg_post_label")
        self.total_positive_label = QtWidgets.QLabel(Form)
        self.total_positive_label.setGeometry(QtCore.QRect(670, 760, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_positive_label.setFont(font)
        self.total_positive_label.setObjectName("total_positive_label")
        self.total_negative_label = QtWidgets.QLabel(Form)
        self.total_negative_label.setGeometry(QtCore.QRect(670, 800, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_negative_label.setFont(font)
        self.total_negative_label.setObjectName("total_negative_label")
        self.avg_polarity_overall_output = QtWidgets.QLabel(Form)
        self.avg_polarity_overall_output.setGeometry(QtCore.QRect(880, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_polarity_overall_output.setFont(font)
        self.avg_polarity_overall_output.setObjectName("avg_polarity_overall_output")
        self.avg_title_length_output = QtWidgets.QLabel(Form)
        self.avg_title_length_output.setGeometry(QtCore.QRect(840, 400, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_title_length_output.setFont(font)
        self.avg_title_length_output.setObjectName("avg_title_length_output")
        self.avg_post_length_output = QtWidgets.QLabel(Form)
        self.avg_post_length_output.setGeometry(QtCore.QRect(840, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_post_length_output.setFont(font)
        self.avg_post_length_output.setObjectName("avg_post_length_output")
        self.total_positive_output = QtWidgets.QLabel(Form)
        self.total_positive_output.setGeometry(QtCore.QRect(810, 760, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_positive_output.setFont(font)
        self.total_positive_output.setObjectName("total_positive_output")
        self.total_negative_output = QtWidgets.QLabel(Form)
        self.total_negative_output.setGeometry(QtCore.QRect(820, 800, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_negative_output.setFont(font)
        self.total_negative_output.setObjectName("total_negative_output")
        self.total_neg_post_label = QtWidgets.QLabel(Form)
        self.total_neg_post_label.setGeometry(QtCore.QRect(670, 620, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_neg_post_label.setFont(font)
        self.total_neg_post_label.setObjectName("total_neg_post_label")
        self.total_pos_post_label = QtWidgets.QLabel(Form)
        self.total_pos_post_label.setGeometry(QtCore.QRect(670, 580, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_pos_post_label.setFont(font)
        self.total_pos_post_label.setObjectName("total_pos_post_label")
        self.avg_pos_score_com_label = QtWidgets.QLabel(Form)
        self.avg_pos_score_com_label.setGeometry(QtCore.QRect(670, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_pos_score_com_label.setFont(font)
        self.avg_pos_score_com_label.setObjectName("avg_pos_score_com_label")
        self.avg_neg_score_com_label = QtWidgets.QLabel(Form)
        self.avg_neg_score_com_label.setGeometry(QtCore.QRect(670, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_neg_score_com_label.setFont(font)
        self.avg_neg_score_com_label.setObjectName("avg_neg_score_com_label")
        self.avg_pos_score_post_label = QtWidgets.QLabel(Form)
        self.avg_pos_score_post_label.setGeometry(QtCore.QRect(670, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_pos_score_post_label.setFont(font)
        self.avg_pos_score_post_label.setObjectName("avg_pos_score_post_label")
        self.avg_neg_score_post_label = QtWidgets.QLabel(Form)
        self.avg_neg_score_post_label.setGeometry(QtCore.QRect(670, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_neg_score_post_label.setFont(font)
        self.avg_neg_score_post_label.setObjectName("avg_neg_score_post_label")
        self.total_pos_com_label = QtWidgets.QLabel(Form)
        self.total_pos_com_label.setGeometry(QtCore.QRect(670, 670, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_pos_com_label.setFont(font)
        self.total_pos_com_label.setObjectName("total_pos_com_label")
        self.total_neg_com_label = QtWidgets.QLabel(Form)
        self.total_neg_com_label.setGeometry(QtCore.QRect(670, 710, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_neg_com_label.setFont(font)
        self.total_neg_com_label.setObjectName("total_neg_com_label")
        self.avg_post_polarity_label = QtWidgets.QLabel(Form)
        self.avg_post_polarity_label.setGeometry(QtCore.QRect(670, 230, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_post_polarity_label.setFont(font)
        self.avg_post_polarity_label.setObjectName("avg_post_polarity_label")
        self.avg_post_polarity_output = QtWidgets.QLabel(Form)
        self.avg_post_polarity_output.setGeometry(QtCore.QRect(850, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_post_polarity_output.setFont(font)
        self.avg_post_polarity_output.setObjectName("avg_post_polarity_output")
        self.avg_com_polarity_label = QtWidgets.QLabel(Form)
        self.avg_com_polarity_label.setGeometry(QtCore.QRect(670, 270, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_com_polarity_label.setFont(font)
        self.avg_com_polarity_label.setObjectName("avg_com_polarity_label")
        self.avg_com_polarity_output = QtWidgets.QLabel(Form)
        self.avg_com_polarity_output.setGeometry(QtCore.QRect(900, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_com_polarity_output.setFont(font)
        self.avg_com_polarity_output.setObjectName("avg_com_polarity_output")
        self.total_pos_post_output = QtWidgets.QLabel(Form)
        self.total_pos_post_output.setGeometry(QtCore.QRect(870, 570, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_pos_post_output.setFont(font)
        self.total_pos_post_output.setObjectName("total_pos_post_output")
        self.total_neg_post_output = QtWidgets.QLabel(Form)
        self.total_neg_post_output.setGeometry(QtCore.QRect(880, 620, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_neg_post_output.setFont(font)
        self.total_neg_post_output.setObjectName("total_neg_post_output")
        self.total_pos_com_output = QtWidgets.QLabel(Form)
        self.total_pos_com_output.setGeometry(QtCore.QRect(920, 660, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_pos_com_output.setFont(font)
        self.total_pos_com_output.setObjectName("total_pos_com_output")
        self.total_neg_com_output = QtWidgets.QLabel(Form)
        self.total_neg_com_output.setGeometry(QtCore.QRect(930, 710, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_neg_com_output.setFont(font)
        self.total_neg_com_output.setObjectName("total_neg_com_output")
        self.total_post_label = QtWidgets.QLabel(Form)
        self.total_post_label.setGeometry(QtCore.QRect(670, 500, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_post_label.setFont(font)
        self.total_post_label.setObjectName("total_post_label")
        self.total_post_output = QtWidgets.QLabel(Form)
        self.total_post_output.setGeometry(QtCore.QRect(790, 500, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_post_output.setFont(font)
        self.total_post_output.setObjectName("total_post_output")
        self.total_com_label = QtWidgets.QLabel(Form)
        self.total_com_label.setGeometry(QtCore.QRect(670, 540, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_com_label.setFont(font)
        self.total_com_label.setObjectName("total_com_label")
        self.total_com_output = QtWidgets.QLabel(Form)
        self.total_com_output.setGeometry(QtCore.QRect(830, 540, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_com_output.setFont(font)
        self.total_com_output.setObjectName("total_com_output")
        self.avg_pos_score_com_output = QtWidgets.QLabel(Form)
        self.avg_pos_score_com_output.setGeometry(QtCore.QRect(930, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_pos_score_com_output.setFont(font)
        self.avg_pos_score_com_output.setObjectName("avg_pos_score_com_output")
        self.avg_neg_score_com_output = QtWidgets.QLabel(Form)
        self.avg_neg_score_com_output.setGeometry(QtCore.QRect(930, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_neg_score_com_output.setFont(font)
        self.avg_neg_score_com_output.setObjectName("avg_neg_score_com_output")
        self.avg_pos_score_post_output = QtWidgets.QLabel(Form)
        self.avg_pos_score_post_output.setGeometry(QtCore.QRect(880, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_pos_score_post_output.setFont(font)
        self.avg_pos_score_post_output.setObjectName("avg_pos_score_post_output")
        self.avg_neg_score_post_output = QtWidgets.QLabel(Form)
        self.avg_neg_score_post_output.setGeometry(QtCore.QRect(880, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_neg_score_post_output.setFont(font)
        self.avg_neg_score_post_output.setObjectName("avg_neg_score_post_output")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(670, 440, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(670, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.date_label = QtWidgets.QLabel(Form)
        self.date_label.setGeometry(QtCore.QRect(40, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_button.setText(_translate("Form", "Retrieve Results"))
        self.topics_label.setText(_translate("Form", "Topics:"))
        self.context_label.setText(_translate("Form", "Context Keywords:"))
        self.raw_text_label.setText(_translate("Form", "Raw Text:"))
        self.subreddit_input_label.setText(_translate("Form", "SUBREDDIT:"))
        self.avg_polarity_overall_label.setText(_translate("Form", "Avg. Polarity Overall:"))
        self.auto_process_button.setText(_translate("Form", "Auto-Process"))
        self.avg_title_label.setText(_translate("Form", "Avg. Title Length:"))
        self.avg_post_label.setText(_translate("Form", "Avg. Post Length:"))
        self.total_positive_label.setText(_translate("Form", "Total Positive:"))
        self.total_negative_label.setText(_translate("Form", "Total Negative:"))
        self.avg_polarity_overall_output.setText(_translate("Form", "N/A"))
        self.avg_title_length_output.setText(_translate("Form", "N/A"))
        self.avg_post_length_output.setText(_translate("Form", "N/A"))
        self.total_positive_output.setText(_translate("Form", "N/A"))
        self.total_negative_output.setText(_translate("Form", "N/A"))
        self.total_neg_post_label.setText(_translate("Form", "Total Negative Posts:"))
        self.total_pos_post_label.setText(_translate("Form", "Total Positive Posts:"))
        self.avg_pos_score_com_label.setText(_translate("Form", "Avg. Pos. Score Comments:"))
        self.avg_neg_score_com_label.setText(_translate("Form", "Avg. Neg. Score Comments:"))
        self.avg_pos_score_post_label.setText(_translate("Form", "Avg. Pos. Score Posts:"))
        self.avg_neg_score_post_label.setText(_translate("Form", "Avg. Neg. Score Posts:"))
        self.total_pos_com_label.setText(_translate("Form", "Total Positive Comments:"))
        self.total_neg_com_label.setText(_translate("Form", "Total Negative Comments:"))
        self.avg_post_polarity_label.setText(_translate("Form", "Avg. Post Polarity:"))
        self.avg_post_polarity_output.setText(_translate("Form", "N/A"))
        self.avg_com_polarity_label.setText(_translate("Form", "Avg. Comments Polarity:"))
        self.avg_com_polarity_output.setText(_translate("Form", "N/A"))
        self.total_pos_post_output.setText(_translate("Form", "N/A"))
        self.total_neg_post_output.setText(_translate("Form", "N/A"))
        self.total_pos_com_output.setText(_translate("Form", "N/A"))
        self.total_neg_com_output.setText(_translate("Form", "N/A"))
        self.total_post_label.setText(_translate("Form", "Total Posts:"))
        self.total_post_output.setText(_translate("Form", "N/A"))
        self.total_com_label.setText(_translate("Form", "Total Comments:"))
        self.total_com_output.setText(_translate("Form", "N/A"))
        self.avg_pos_score_com_output.setText(_translate("Form", "N/A"))
        self.avg_neg_score_com_output.setText(_translate("Form", "N/A"))
        self.avg_pos_score_post_output.setText(_translate("Form", "N/A"))
        self.avg_neg_score_post_output.setText(_translate("Form", "N/A"))
        self.label.setText(_translate("Form", "TOTALS"))
        self.label_2.setText(_translate("Form", "AVERAGES"))
        self.date_label.setText(_translate("Form", "DATE:"))

